### ISSUE TITLE
num-traits Implementation 

### ISSUE THREAD

**Issue by NatanFreeman** [stencillogic/num-bigfloat#1]
Could [num-traits](https://crates.io/crates/num-traits) be implemented for `BigFloat` with the use of a feature flag? This would make it useable for libraries that depend on it.

**Comment by stencillogic** [comment]
Hey Natan. This is great that you brought this up. I am currently in attempt to make this library fully arbitrary precision, so can't tell when I will be able to address this one. Also, pull requests are welcome 😊

**Comment by NatanFreeman** [comment]
I'll give it a shot. We'll see what becomes of it.

**Comment by stencillogic** [comment]
Hi @NatanFreeman ,
How is it going with [num-traits](https://crates.io/crates/num-traits) implementation? Are there questions/challenging parts I could help with?

**Comment by stencillogic** [comment]
@NatanFreeman  I'll take this one if you don't mind.

**Comment by stencillogic** [comment]
Support for num-traits added. The issue will be closed soon.

**Comment by stencillogic** [comment]
Closing this issue as completed.

**Comment by NatanFreeman** [comment]
I was unable to implement this feature. I am glad @stencillogic stepped up to the task. 🦀🚀🚀

**Comment by stencillogic** [comment]
Hi @NatanFreeman,
Sorry. I decided to take this task, because I didn't hear from you. If you have something done already, and you think you have done some parts better, you can always open a pull request for discussion.
If a task looks scary difficult it can always be split into pieces and done with small steps. It works for me at least.
If you have doubts about how to implement certain things, I'd recommend to go to community forums/chats, and as soon as you feel it is completed just open a pull request for discussion. Even if you are not sure if it is done correctly, it would be no problem. Pull requests as well as new issues are welcome 😊

**Comment by NatanFreeman** [comment]
No problem. It was a while since I've attempted this. I'll have to be more active in the future.
